import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>RaffleTok . CryptolisDAO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3>Powered By CryptolisDAO</h3>
        <h1 className={styles.title}>Welcome to the world of exciting raffles</h1>
        <h5>
          എന്താടാ മൈരേ നോക്കുന്നേ ? പണി എടുത്താലേ ആപ്പ് ഉണ്ടാകൂ !! അല്ലാതെ ചുമ്മാ കേറി നോക്കിയാൽ
          മാനത്തു നിന്ന് update വരില്ല !!
        </h5>
      </main>
      <p className={styles.description}>Take your NFTs, split into tickets, sell !!</p>
    </div>
  );
}
